services:
  mainserver:
    container_name: tuxbase-mainserver
    build: .
    ports:
      - "13000:13000"
    volumes:
      - ../Src:/root/src
      - ../../03_Share:/root/share
    command: sleep infinity

  dummyclient:
    container_name: tuxbase-dummyclient
    build: .
    volumes:
      - ../Src:/root/src
      - ../../03_Share:/root/share
    depends_on:
      - mainserver
    command: sleep infinity
