services:
  mainserver:
    container_name: tuxbase-mainserver
    build: .
    ports:
      - "13000:13000"
    volumes:
      - ../Src:/root/src
    command: /bin/bash /root/src/98_Scripts/Entrypoint.sh server

  dummyclient:
    container_name: tuxbase-dummyclient
    build: .
    volumes:
      - ../Src:/root/src
    depends_on:
      - mainserver
    command: /bin/bash /root/src/98_Scripts/Entrypoint.sh client
